joint1_choreograph:
  joint_index: 0
  section1:
    start_time_delay: 1.
    end_time_delay: 1.
    active_time: 7.
    start_joint_positions: [0., 0., 0., 0., 0., 0.]
    control_signal:
      type: "step"
      value: 0.1
      delay_time: 2.
  section2:
    start_time_delay: 1.
    end_time_delay: 1.
    active_time: 2.
    start_joint_positions: [0., 0., 0., 0., 0., 0.]
    control_signal:
      type: "step"
      value: -0.78
      delay_time: 1.
  section3:
    start_time_delay: 1.
    end_time_delay: 1.
    active_time: 2.5
    start_joint_positions: [0., 1.57, 3.14, 0., 0., 0.]
    control_signal:
      type: "step"
      value: 1.
      delay_time: 1.
  section4:
    start_time_delay: 1.
    end_time_delay: 1.
    active_time: 1.75
    start_joint_positions: [1.5, 1.57, 3.14, 0., 0., 0.]
    control_signal:
      type: "step"
      value: -3.
      delay_time: 1.
  section5:
    start_time_delay: 1.
    end_time_delay: 1.
    active_time: 1.
    start_joint_positions: [-1.5, 1.57, 3.14, 0., 0., 0.]
    control_signal:
      type: "sine"
      amplitude: 3.
      frequency: 1.
  section6:
    start_time_delay: 1.
    end_time_delay: 1.
    active_time: 5.
    start_joint_positions: [1.5, 1.57, 3.14, 0., 0., 0.]
    control_signal:
      type: "sine"
      amplitude: -1.
      frequency: 2.
  section7:
    start_time_delay: 1.
    end_time_delay: 1.
    active_time: 10.
    start_joint_positions: [-1.5, 1.57, 3.14, 0., 0., 0.]
    control_signal:
      type: "sine"
      amplitude: 0.2
      frequency: 3.

   
      
